packages:
  - "."

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false

blockExoticSubdeps: true

verifyDepsBeforeRun: install

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@5.7.2 || 6.3.1'

minimumReleaseAge: 10080
overrides:
  rolldown: 1.2.5
