name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

    # paths-ignore:
    #   - "**/*.md"
    #   - "docs/**"

  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  osv-scan:
    name: OSV Scanner
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@6e4298ebc4db23e847df9b2e2de2939d6f066c67 # v2.5.1
        with:
          scan-args: |-
            --lockfile=pnpm-lock.yaml

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          # nix/fixed-node.nix のバージョンと合わせる
          node-version: "24.21.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Test
      #   run: pnpm test

      # - name: Typecheck
      #   run: pnpm typecheck

      - name: Check lint script
        id: lint-script
        run: |
          if pnpm pkg get scripts.lint | grep -qv '^{}$'; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint
        if: steps.lint-script.outputs.exists == 'true'
        run: pnpm lint

      - name: Build
        run: pnpm build
